# Generated by Django 5.1 on 2025-06-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_mediafile_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stat',
            field=models.CharField(choices=[('1', 'Не рассмотрен'), ('2', 'Принят'), ('0', 'Отклонён')], default='1', max_length=1),
        ),
    ]
